# Site
name: 'Tin10'
description: 'Tin 10 is a blog that will list the translated Vietnamese version of my English/Korean favorite news/articles.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'hungphan88@gmail.com'
languages: ["vi"]
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    hungphan88:
      name:           Hưng Phan
      site:           https://hungph.github.io
      avatar:         assets/images/avatar1.jpg
      bio:            "Xin chào, mình là Hưng, một lập trình viên, thích dịch báo (hungphan88@gmail.com)!"
      email:          hungphan88@gmail.com
      twitter:        https://twitter.com/hungphan88
      facebook:       https://www.facebook.com/hungphan88

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: hungphan88
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]